### ISSUE TITLE
[Question] How often is the live CSV file updated

### ISSUE THREAD

**Issue by nicolas-raoul** [alemela/wiki-needs-pictures#12]
How often is https://tools.wmflabs.org/wiki-needs-pictures/data/data.csv updated?

Because 7 MB is costly for mobile users, I am implementing a cache mechanism at https://github.com/commons-app/ShootMe/issues/6 and I would like to know how often I should invalidate the cache.

Thanks a lot for maintaining this CSV file! :-)

**Comment by alemela** [comment]
When fully implemented once a day. For now is freezed because of high dimensions. Waiting for #10 to restart the batch.
