### ISSUE TITLE
Switch to maps.wikimedia.org

### ISSUE THREAD

**Issue by nemobis** [alemela/wiki-needs-pictures#2]
Any special reason to use MapQuest? Nowadays we can use maps.wikimedia.org and avoid sending private data outside the WMF cluster. Seems just a matter of rewriting one URL in the config, AFAICS: https://www.mediawiki.org/wiki/Maps#Getting_started

**Comment by alemela** [comment]
Done with https://github.com/alemela/wiki-needs-pictures/commit/3f6534d27d4cbb96b94a4601a0765b1b0abb5bc9
