### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by nicolas-raoul** [alemela/wiki-needs-pictures#3]
The demo does not seem to work over HTTPS: https://tools.wmflabs.org/wiki-needs-pictures/

We would like to use this webapp, but for privacy of our journalists/witnesses users in all sorts of countries, all traffic should be over HTTPS.

Also, is it possible to avoid non-Wikimedia domains? Right now I see requests to mqcdn.com

Thanks!

**Comment by alemela** [comment]
Now should work also with HTTPS, thanks for the issue!

**Comment by nicolas-raoul** [comment]
Cool, now all requests are made in HTTP to only Wikimedia-owned domains: tools.wmflabs.org tools-static.wmflabs.org maps.wikimedia.org
Thanks! :-)
