### ISSUE TITLE
[enhancement] List backend dependencies in package.json

### ISSUE THREAD

**Issue by nicolas-raoul** [alemela/wiki-needs-pictures#5]
It would make it much easier to run the backend.
https://docs.npmjs.com/getting-started/using-a-package.json
Thanks!

**Comment by alemela** [comment]
Sure! Done via https://github.com/alemela/wiki-needs-pictures/commit/b17b8fbb2e0485c6e179e4b297b6856b5ccf1a39

**Comment by nicolas-raoul** [comment]
Thanks :-)
